import DashboardDrawer from "@/components/Dashboard/DashbordDrawer/DashboardDrawer";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="">
      <DashboardDrawer>{children}</DashboardDrawer>
    </div>
  );
};

export default DashboardLayout;
