import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/lib/Providers/Providers";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Toaster
            position="top-center"
            toastOptions={{
              unstyled: true,
              classNames: {
                error: "text-[#ff3333]",
                success: "text-[#22bb33]",
              },
            }}
          />
          <div className="min-h-screen container">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
